version: '2'
services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2017-latest
    command: /bin/bash ./entrypoint.sh
    ports:
     - 1433:1433
    environment:
     - ACCEPT_EULA=Y
     - MSSQL_PID=Standard
     - SA_PASSWORD=Password!
     - MSSQL_AGENT_ENABLED=true
    volumes:
      - dbdata:/var/opt/mssql/data
      - ./scripts/docker-entrypoint.sh:/entrypoint.sh
      - ./scripts/docker-db-init.sh:/db-init.sh
      - ./scripts/create-table.sql:/db-init.sql
      
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    links:
     - sqlserver
    environment:
      - ADM_INSTALL_MSSQL=true
      - PHP_FPM_INSTALL_MSSQL=true
      - WORKSPACE_INSTALL_MSSQL=true

volumes:
  dbdata: